### PR TITLE
bootstrap-sass => boostrap-sass-official

### PR DESCRIPTION
**Pull request by samselikoff**

### CODE REVIEW

**Comment by yankeeinlondon** [comment]
@samselikoff I've been focused elsewhere but just looking at the Travis builds it would appear that this change breaks the build (it builds fine with the old 'bootstrap-sass'). I think that maybe the problem is that I haven't published the latest to npm. Let me do that now and let me know if that solves your problem (the new one is 0.0.13 on npm.

**Comment by noelrappin** [comment]
I'm seeing `
Path or pattern "bower_components/bootstrap-sass/assets/javascripts/bootstrap.js" did not match any files` with 0.0.13

**Comment by yankeeinlondon** [comment]
Ok, having looked ... I believe that the old nomenclature of "bootstrap-sass-official" has been replaced by the more compact "bootstrap-sass". Please let me know if you think otherwise. 

The reason there were problems is that while the addon's `bower.json`, and the `index.js` both use the "bootstrap-sass" (_correct_) but the blueprint was still telling container to install the "bootstrap-sass-official"  bower module (_incorrect_ but still works) so users had a disconnect on where they installed versus where the addon was looking for it.

Ok, a bit long winded. Quick fix coming.

**Comment by yankeeinlondon** [comment]
Fixed and available as 0.0.14. You'll need to rerun the `ember addon:install` command to have it re-execute the blueprint or maybe more straight froward:

```
npm update ember-cli-bootstrap-sassy
ember g ember-cli-bootstrap-sassy
```

Happy trails.

**Comment by yankeeinlondon** [comment]
image

Will close for now. Feel free to open again if there is still an issue.

**Comment by samselikoff** [comment]
thanks a lot @ksnyde !

**Pull request closed without merging**
