### PR TITLE
Fix importBootstrapJS option.

### PR DESCRIPTION
**Pull request by akisvolanis**
Fix importBootstrapJS option for importing Bootstrap's JS libraries as described in README file.

### CODE REVIEW

**Comment by yankeeinlondon** [comment]
Just out of interest, are you developing on Windows?

**Comment by akisvolanis** [comment]
nope. i'm on osx. why?

**Comment by yankeeinlondon** [comment]
Ok so I guess it's not a Windows thing. I just saw you're README comment and that should be changed to make it consistent but are there any problems you're experiencing? I currently am using it in the "all on" mode and it appears to work fine but there are a plenty of edge cases I haven't tested.

**Comment by akisvolanis** [comment]
no, i prefer the short names too, so i'm good to go with `js` name. About the use of path_join, that was the one solution :) the other one was to fix your typo(replace the `,` with `+` in `app.import(bootstrapPath + 'javascripts/bootstrap', fileName + '.js');`). It's up to you, as both works fine.

**Comment by yankeeinlondon** [comment]
Ahhh. All the caffeine in the world will stop me from fat fingering things. Thanks for catching it. Do you want to update the PR or shall I just make the change (I've already made the README change)

**Comment by akisvolanis** [comment]
:) i'll do it. no prob..

**Pull request closed without merging**
