### PR TITLE
woff2 font file to be imported from bootstrap

### PR DESCRIPTION
**Pull request by bdtomlin**
The woff2 file was not being imported, which would cause a 404 error.

### CODE REVIEW

**Comment by yankeeinlondon** [comment]
Thanks @bdtomlin ... good catch.

**Comment by yankeeinlondon** [comment]
@bdtomlin I should have paid a bit more attention but seems we're getting a failure now on the component. Can you have a look?

image

http://clicks.travis-ci.org/track/click/30007208/travis-ci.org?p=eyJzIjoicXQ3eHZQbjFKdkRMc3A0SzNrNXgxb1J0M01VIiwidiI6MSwicCI6IntcInVcIjozMDAwNzIwOCxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL3RyYXZpcy1jaS5vcmdcXFwvbGlmZWdhZGdldFxcXC9lbWJlci1jbGktYm9vdHN0cmFwLXNhc3N5XCIsXCJpZFwiOlwiMTZjZjExMDNiMTgxNDNhMmI3YjdlMDEyNjYxMTM2NDJcIixcInVybF9pZHNcIjpbXCJjMDViODE3ZjVlN2ZjYTlmMTE3ZTBhOWE1OWZmMjc0OThmN2NjN2QwXCJdfSJ9

**Comment by bdtomlin** [comment]
The same error is happening on the master branch as well. I'll look at it.

On Wed, Mar 18, 2015 at 9:00 AM, Ken Snyder notifications@github.com
wrote:

> @bdtomlin https://github.com/bdtomlin I should have paid a bit more
> attention but seems we're getting a failure now on the component. Can you
> have a look?
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/980757/6710245/1976d0ec-cd77-11e4-971d-4f0036119adb.png
> 
> http://clicks.travis-ci.org/track/click/30007208/travis-ci.org?p=eyJzIjoicXQ3eHZQbjFKdkRMc3A0SzNrNXgxb1J0M01VIiwidiI6MSwicCI6IntcInVcIjozMDAwNzIwOCxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL3RyYXZpcy1jaS5vcmdcXFwvbGlmZWdhZGdldFxcXC9lbWJlci1jbGktYm9vdHN0cmFwLXNhc3N5XCIsXCJpZFwiOlwiMTZjZjExMDNiMTgxNDNhMmI3YjdlMDEyNjYxMTM2NDJcIixcInVybF9pZHNcIjpbXCJjMDViODE3ZjVlN2ZjYTlmMTE3ZTBhOWE1OWZmMjc0OThmN2NjN2QwXCJdfSJ9
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/lifegadget/ember-cli-bootstrap-sassy/pull/9#issuecomment-82986625
> .

## 

Bryan Tomlin

**Comment by bdtomlin** [comment]
It's something with the particular version of ember cli being used. I
upgraded to ember-cli 0.2.0 and everything builds fine.

On Wed, Mar 18, 2015 at 2:36 PM, Bryan Tomlin bt@bryantomlin.com wrote:

> The same error is happening on the master branch as well. I'll look at it.
> 
> On Wed, Mar 18, 2015 at 9:00 AM, Ken Snyder notifications@github.com
> wrote:
> 
> > @bdtomlin https://github.com/bdtomlin I should have paid a bit more
> > attention but seems we're getting a failure now on the component. Can you
> > have a look?
> > 
> > [image: image]
> > https://cloud.githubusercontent.com/assets/980757/6710245/1976d0ec-cd77-11e4-971d-4f0036119adb.png
> > 
> > http://clicks.travis-ci.org/track/click/30007208/travis-ci.org?p=eyJzIjoicXQ3eHZQbjFKdkRMc3A0SzNrNXgxb1J0M01VIiwidiI6MSwicCI6IntcInVcIjozMDAwNzIwOCxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL3RyYXZpcy1jaS5vcmdcXFwvbGlmZWdhZGdldFxcXC9lbWJlci1jbGktYm9vdHN0cmFwLXNhc3N5XCIsXCJpZFwiOlwiMTZjZjExMDNiMTgxNDNhMmI3YjdlMDEyNjYxMTM2NDJcIixcInVybF9pZHNcIjpbXCJjMDViODE3ZjVlN2ZjYTlmMTE3ZTBhOWE1OWZmMjc0OThmN2NjN2QwXCJdfSJ9
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/lifegadget/ember-cli-bootstrap-sassy/pull/9#issuecomment-82986625
> > .
> 
> ## 
> 
> Bryan Tomlin

## 

Bryan Tomlin

**Pull request merged**
