### PR TITLE
move broccoli-funnel to dependencies.

### PR DESCRIPTION
**Pull request by akisvolanis**
Moving broccoli-funnel to addon dependencies will install it as a dependency for the addon in the installation process.

### CODE REVIEW

**Comment by akisvolanis** [comment]
still travis is failing. same issue as https://github.com/lifegadget/ember-cli-bootstrap-sassy/issues/14

**Comment by yankeeinlondon** [comment]
Oh cool, that's handy to know how easy an npm dependency like that is met. Also thanks for fitting this in considering how busy you are.

**Comment by yankeeinlondon** [comment]
What do you think about moving back to 3.1 of ember-cli-sass? I think we should do it unless you're aware of an imminent fix on the 3.2.x releases.

**Comment by akisvolanis** [comment]
no problem at all. yes i think it's ok for now. i'm already using v3.1 without any issue.

**Comment by akisvolanis** [comment]
also can you confirm that is ok now with broccoli-funnel dependency?

**Comment by yankeeinlondon** [comment]
about to run into a series of meetings but will check later today

**Comment by akisvolanis** [comment]
ok great. thanks.

**Comment by yankeeinlondon** [comment]
@charlatan154 down with a flu so it took longer than expected but upon inspection your "npm magic" seems to work funnel magic. Thanks. :)

**Comment by akisvolanis** [comment]
nice to hear that it's working now. hope you get well soon.

**Pull request merged**
