### PR TITLE
Update to Ember 2.18 - fix #53

### LINKED ISSUE #53: Deprecation alert in Ember v2.18 apps
A new deprecation message is started to appear after upgrading to Ember v2.18.

```
An addon is trying to access project.nodeModulesPath. This is not a reliable way to discover npm modules. Instead, consider doing: require("resolve").sync(something, { basedir: project.root }). Accessed from:   new NPMDependencyVersionChecker ... 
```

### PR DESCRIPTION
**Pull request by zoltan-nz**
* Upgrade using ember-cli v2.18
* Update `index.js` using ES6 syntax

### CODE REVIEW

**Comment by zoltan-nz** [comment]
Travis had an `ETIMEDOUT`... Can we trigger a new build, maybe?

**Comment by yankeeinlondon** [comment]
I will do this when home. Was trying to fly to LA but flight was cancelled so back near home in London but needed a drink first. :)

**Comment by yankeeinlondon** [comment]
Actually I’ve kicked it off from the pub

**Comment by zoltan-nz** [comment]
Hey Ken. Thanks for that and hope the drink was great and you got some
other flight to get to LA. :)

**Comment by zoltan-nz** [comment]
Hi @ksnyde, if you think, that everything right, maybe there could be a new release of npm package with a minor version bump. What's do you think?

**Comment by yankeeinlondon** [comment]
Will do. Back at airport atm.

Ken
ken@ken.net

**Comment by yankeeinlondon** [comment]
image

all done

**Comment by zoltan-nz** [comment]
Wow, thank you! We just had our www.yoember.com workshop an hour ago here
in Wellington, and we already started to use the new version. Thank you! :)

**Pull request merged**
