### PR TITLE
Fix typos.

### PR DESCRIPTION
**Pull request by akisvolanis**
I thing it's ok from typos at last.

### CODE REVIEW

**Comment by yankeeinlondon** [comment]
The first fix you suggest here has already been fixed. Don't think the second one is appropriate as `bootstrapPath` is already defined to have the trailing forward slash. Is there really any issues left to fix? It passes CI and works fine for me.

```
var bootstrapPath   = 'bower_components/bootstrap-sass-official/assets/';
```

**Comment by akisvolanis** [comment]
i think it needs a forward slash here `'javascripts/bootstrap/'` at the end. bootstrapPath is ok.

**Comment by yankeeinlondon** [comment]
yes you're right. I can't merge PR as is but if you remove the other fix I'm happy to accept this. otherwise happy to make the quick change myself but don't want to take away credit where credit is due.

**Comment by akisvolanis** [comment]
i thing you are good to go. :) Also i think it's a good idea to have the option to opt out the logs if you want.

**Comment by yankeeinlondon** [comment]
I like the option of opting out the logs ... was also _considering_ adding optional addition of having font-awesome icons so that someone can opt-out of glyphicons and at the same time opt-in to font-awesome (which I think many prefer). What do you think?

**Comment by yankeeinlondon** [comment]
I think the problem that stopped me with opt-in to font-awesome is that I'm not sure I can conditionally install font-awesome so maybe its better left out?

**Comment by akisvolanis** [comment]
I'm using font-awsome too, opting out glyphicons, but i think it's better to have the choice if and how i would import font-awsome as there are other, more sophisticated solutions, like ember-cli-font-awesome addon.

**Pull request merged**
